[package]
name = "geode-cli"
version = "0.2.3"
authors = ["HJfod <dreadrollmusic@gmail.com>", "Camila314 <ilaca314@gmail.com>"]
edition = "2018"
build = "build.rs"

[[bin]]
name = "geode"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[target.'cfg(windows)'.build-dependencies]
winres = "0.1" # for icon

[target.'cfg(windows)'.dependencies]
winapi = "0.3"
winreg = "0.10"
windows = { version = "0.32.0", features = ["Win32_UI_Shell"] }
const_format = "0.2.13"

[dependencies]
clap = { version = "3.0.12", features = ["derive"] }
colored = "2"
directories = "4.0.1"
fontdue = "0.7.2"
geode-utils = { path = "./lib" }
git2 = "0.13.25"
glob = "0.3.0"
home = "0.5.3"
image = "0.23.14"
imageproc = "0.22.0"
indicatif = "0.16.2"
libc = "0.2.0"
path-absolutize = "3.0.11"
plist = "1.3.1"
rustyline = "9.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
sha256 = "1.0.3"
sysinfo = "0.23.0"
texture_packer = "0.23.1"
walkdir = "2"
zip = "0.5.13"
