[package]
name = "cli"
version = "0.1.0"
authors = ["HJfod <60038575+HJfod@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = { version = "3.0.12", features = ["derive"] }
path-absolutize = "3.0.11"
