[package]
name = "geode-cli"
version = "0.1.0"
authors = ["HJfod <60038575+HJfod@users.noreply.github.com>"]
edition = "2018"

[[bin]]
name = "geode"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
clap = { version = "3.0.12", features = ["derive"] }
path-absolutize = "3.0.11"
rustyline = "9.1.0"
rustyline-derive = "0.6.0"
serde_json = { version = "1.0", features = ["preserve_order"] }
