[package]
name = "geode-cli"
version = "0.3.0"
authors = ["HJfod <dreadrollmusic@gmail.com>", "Camila314 <ilaca314@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
colored = "2"
git2 = "0.13.25"
path-absolutize = "3.0.11"
rustyline = "9.1.0"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
zip = "0.5.13"
glob = "0.3.0"
sha256 = "1.0.3"
dirs = "4.0.0"
directories = "4.0.1"
fontdue = "0.7.2"
texture_packer = "0.24.0"

[build-dependencies]
winres = "0.1.12"
