name: Build Binaries

on:
  push:
    tags:
    - '*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "Windows"
          os: windows-latest
          zip: "7z a -tzip ${{ github.workspace }}/Windows.zip ${{ github.workspace }}/build/release/geode.exe"
        - name: "macOS"
          os: macos-latest
          zip: "zip ${{ github.workspace }}/macOS.zip ${{ github.workspace }}/build/release/geode"
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: |
        cargo build --release --target-dir ${{ github.workspace }}/build     
    
    - name: Archive Release
      run: |
        cd . &&
        ${{ matrix.config.zip }}
    
    - name: Publish Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "${{ github.workspace }}/${{ matrix.config.name }}.zip"
        token: ${{ secrets.GEODE_BOT_PUSH_BIN_TOKEN }}
