name: Build Binaries

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: "Windows"
          os: windows-latest
          path: build/release/geode.exe
#        - name: "macOS"
#          os: macos-latest
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build
      run: |
        cargo build --release --target-dir ${{ github.workspace }}/build     
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.config.name }} Build
        path: ${{ github.workspace }}/${{ matrix.config.path }}
